import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
const cli = fileURLToPath(new URL('../../../apps/cli/dist/index.js', import.meta.url));
const run = (args: string[]) => JSON.parse(execFileSync(process.execPath, [cli, ...args], { cwd: tmpdir(), windowsHide: true, encoding: 'utf8' }));
const workflow = run(['playbook', 'layered', 'workflow']);
assert.equal(workflow.externalModelCalls, 0); assert.ok(workflow.schemas.plan); assert.ok(workflow.schemas.review);
const automatic = run(['playbook', 'recommend', '--format', 'story', '--goal', 'Edit my daily vlog']);
assert.equal(automatic.styleProfile.id, 'dimit-visual-journal'); assert.match(automatic.styleProfile.instructions, /environment/);
const disabled = run(['playbook', 'recommend', '--format', 'story', '--goal', 'Edit my daily vlog', '--profile', 'none']);
assert.equal(disabled.styleProfile, null);
const generic = run(['playbook', 'recommend', '--format', 'story', '--goal', 'Assemble a story']);
assert.equal(generic.styleProfile, null);
const packaging = run(['playbook', 'recommend', '--task', 'package', '--goal', 'SEO for my vlog']);
assert.equal(packaging.styleProfile, null);
const wrong = spawnSync(process.execPath, [cli, 'playbook', 'recommend', '--task', 'package', '--goal', 'SEO', '--profile', 'dimit-visual-journal'], { cwd: tmpdir(), encoding: 'utf8', windowsHide: true });
assert.notEqual(wrong.status, 0);
console.log(JSON.stringify({ passed: true, desktopRequired: false, paidCalls: 0, checks: ['layered discovery', 'repo default outside cwd', 'explicit opt-out', 'generic edit exclusion', 'copy-only exclusion'] }));
