/** Self-contained local viewer. No remote assets, fetch, telemetry or autoplay audio. */
export function referenceViewer(data:{frames:Array<{index:number;time:number;path:string}>;start:number;end:number;width:number;height:number}) {
  const json=JSON.stringify(data).replace(/</g,'\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' file:; script-src 'unsafe-inline'; style-src 'unsafe-inline'; connect-src 'none'; base-uri 'none'; form-action 'none'">
<title>Frame-by-frame reference</title><style>
*{box-sizing:border-box}body{margin:0;padding:20px;background:#101418;color:#edf4f6;font:16px system-ui}header,nav,aside{max-width:1200px;margin:0 auto 14px}h1{font-size:22px;margin:0 0 8px}button,input,select{font:inherit}button,select{background:#243541;color:white;border:1px solid #56717f;border-radius:6px;padding:7px 12px}nav{display:flex;gap:12px;align-items:center;flex-wrap:wrap}#seek{flex:1;min-width:220px}#viewport{overflow:auto;background:#080b0d;max-height:75vh;border:1px solid #344954}#stage{position:relative;margin:auto;width:fit-content;line-height:0}#main{display:block;max-width:min(100%,1200px);height:auto}#previous{position:absolute;inset:0;width:100%;height:100%;pointer-events:none;opacity:.35;display:none}#readout{font-variant-numeric:tabular-nums}small{color:#a8bac4}label{white-space:nowrap}#coordinates{margin-top:10px}</style>
<header><h1>Frame-by-frame reference</h1><div id="readout"></div><small>Native-resolution decoded frames · source timestamps · visual evidence, not an animation interpretation</small></header>
<nav><button id="back">← Previous</button><button id="play">Play</button><button id="next">Next →</button><input id="seek" aria-label="Frame" type="range" min="0" step="1"><label><input type="checkbox" id="onion"> Previous-frame overlay</label><label><input type="checkbox" id="native"> Native size</label><select id="speed" aria-label="Playback speed"><option value="1">1×</option><option value="0.25">¼×</option><option value="0.1">⅒×</option></select></nav>
<div id="viewport"><div id="stage"><img id="main" alt="Current reference frame"><img id="previous" alt="Previous-frame overlay"></div></div>
<aside><div id="coordinates">Move over the picture for source coordinates.</div><p><small>Arrow keys step through every frame. Playback is best-effort and may lag while images load; frame timestamps are authoritative. No audio is included. Repeated pictures are retained, not deduplicated.</small></p></aside>
<script>const data=${json};const $=id=>document.getElementById(id);let i=0,timer=null,playing=false;const seek=$('seek'),picture=$('main');seek.max=data.frames.length-1;
function stop(){playing=false;clearTimeout(timer);$('play').textContent='Play'}
function show(){const f=data.frames[i];picture.src=f.path;seek.value=i;$('previous').src=data.frames[Math.max(0,i-1)].path;$('previous').style.display=$('onion').checked&&i?'block':'none';$('readout').textContent='Frame '+i+' / '+(data.frames.length-1)+' · source '+f.time.toFixed(6)+' s · range '+data.start+'–'+data.end+' s · '+data.width+'×'+data.height;}
function step(n){stop();i=Math.max(0,Math.min(data.frames.length-1,i+n));show()}
function tick(){if(!playing)return;const interval=i+1<data.frames.length?data.frames[i+1].time-data.frames[i].time:data.end-data.frames[i].time;timer=setTimeout(()=>{if(i+1===data.frames.length){stop();return;}i++;show();tick()},Math.max(1,1000*interval/Number($('speed').value)));}
$('back').onclick=()=>step(-1);$('next').onclick=()=>step(1);seek.oninput=()=>{stop();i=Number(seek.value);show()};$('play').onclick=()=>{if(playing){stop();return}if(i===data.frames.length-1)i=0;playing=true;$('play').textContent='Pause';show();tick()};$('onion').onchange=show;$('native').onchange=()=>{picture.style.maxWidth=$('native').checked?'none':''};$('speed').onchange=stop;
document.onkeydown=e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='SELECT')return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();step(e.key==='ArrowLeft'?-1:1)}};
picture.onmousemove=e=>{const r=picture.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;$('coordinates').textContent='Source x='+Math.round(x*data.width)+' y='+Math.round(y*data.height)+' · normalized '+x.toFixed(4)+', '+y.toFixed(4)};show();</script></html>`;
}
